version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  subscription-service:
    build: ./subscription-service
    container_name: subscription-service
    ports:
      - "3002:3002"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/subscription-db
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      - mongodb
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - '3030:3030'
    depends_on:
      - subscription-service
    environment:
      SUBSCRIPTION_SERVICE_URL: 'http://subscription-service:3002'
      API_KEY: 'a7c311a2ecfa2db6270252411dac415535d3d4ccf8d8935abbdae563fe3bb693e85cde1be81f80296ec55cc65c64bd5325aa126849e9ac773038115cbdb1214c'

  public-service:
    build: ./public-service
    container_name: public-service
    ports:
      - '3001:3001'
    depends_on:
      - api-gateway
    environment:
      API_GATEWAY_URL: 'http://api-gateway:3030'
      API_KEY: 'a7c311a2ecfa2db6270252411dac415535d3d4ccf8d8935abbdae563fe3bb693e85cde1be81f80296ec55cc65c64bd5325aa126849e9ac773038115cbdb1214c'